### ISSUE TITLE
Implement multipart/form uploads

### ISSUE THREAD

**Issue by zikani03** [zikani03/calendago#2]
Clients/Users should be able to upload images via a `multipart/form` request.
The images should be stored to a directory specified by the `CALENDAGO_WORK_DIR` environment variable.

**Comment by TgkCapture** [comment]
I will also need to create a server right?

**Comment by zikani03** [comment]
In a way, initially you just have to modify the `HandleFunc` at https://github.com/zikani03/calendago/blob/7e84c7a54177447ca78d0a7b886b91e92732fae1/main.go#L12-L15

**Comment by TgkCapture** [comment]
Understood
